import { Room } from "@/types/ha";

export const rooms: Room[] = [
  {
    id: "living-room",
    name: "Living Room",
    icon: "mdi:sofa",
    color: "var(--color-room-living)",
    lightGroup: "light.living_room_lights",
    lights: ["light.living_room_tall_lamp", "light.shelf_lamp"],
    tempSensor: "sensor.living_room_temperature",
    humiditySensor: "sensor.living_room_humidity",
    mediaplayers: ["media_player.living_room_tv", "media_player.living_room_nest"],
  },
  {
    id: "bedroom",
    name: "Bedroom",
    icon: "mdi:bed",
    color: "var(--color-room-bedroom)",
    lightGroup: "light.bedroom_lights",
    lights: ["light.strip", "light.bedroom_diffuser", "switch.bedroom_tall_lamp"],
    tempSensor: "sensor.bedroom_temp_humidity_temperature",
    humiditySensor: "sensor.bedroom_temp_humidity_humidity",
    mediaplayers: ["media_player.bedroom_display"],
  },
  {
    id: "office",
    name: "Office",
    icon: "mdi:desk",
    color: "var(--color-room-office)",
    lightGroup: "light.office_lights",
    lights: ["light.office_lamp", "light.office_light_panels"],
    tempSensor: "sensor.office_temp_humidity_temperature",
    humiditySensor: "sensor.office_temp_humidity_humidity",
    mediaplayers: ["media_player.office_display"],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    icon: "mdi:pot-steam",
    color: "var(--color-room-kitchen)",
    lightGroup: "light.kitchen_lights",
    lights: [
      "light.hue_color_spot_1",
      "light.hue_color_spot_2",
      "light.extended_color_light_1",
      "light.extended_color_light_2",
      "light.extended_color_light_3",
      "light.extended_color_light_4",
    ],
    tempSensor: "sensor.kitchen_temp_humidity_temperature",
    humiditySensor: "sensor.kitchen_temp_humidity_humidity",
    mediaplayers: ["media_player.kitchen_display"],
  },
  {
    id: "library",
    name: "Library",
    icon: "mdi:bookshelf",
    color: "var(--color-room-library)",
    lightGroup: "switch.library_smart_plug",
    lights: ["switch.library_smart_plug"],
    tempSensor: "sensor.library_temp_humidity_temperature",
    humiditySensor: "sensor.library_temp_humidity_humidity",
    mediaplayers: [],
  },
];
